### ISSUE TITLE
Add openFPGALoader

### ISSUE THREAD

**Issue by asinghani** [CarlFK/pici#12]
In order to flash the FPGAs, openFPGALoader is probably going to be useful (it's definitely the easiest flashing tool to use). I believe it is not currently packaged for aarch64 anywhere (except as part of oss-cad-suite, but you likely don't want the whole suite since it's a large file + almost all of it is stuff you don't want to run on a RasPi anyways).

https://github.com/trabucayre/openFPGALoader

**Comment by CarlFK** [comment]
https://packages.debian.org/bookworm/openfpgaloader
Package: openfpgaloader (0.10.0+git20230202-edea24f-1) 
git2023 02 02 - hope this is recent enough?
reopen if we want a newer revision.

also found so why not?
openwince-jtag
