### ISSUE TITLE
Add pip + pyserial + tqdm + numpy

### ISSUE THREAD

**Issue by asinghani** [CarlFK/pici#13]
The UART on the FPGA should be passed through to the Pi, would be extremely handy to be able to use Python scripts to talk to it. Having some general convenience packages + pip itself would also be nice for making life easier.

**Comment by CarlFK** [comment]
'''
+      - python3-full
+      - python3-pip
+      - python3-tqdm
+      - python3-numpy
'''
easy, done.

> UART on the FPGA should be passed through to the Pi
Is there something here that needs to happen? 

would this help? 
python3-serial

**Comment by asinghani** [comment]
> UART on the FPGA should be passed through to the Pi

I believe it already is, but have not gotten a chance to test it yet. Will report back if there's an issue with it

> python3-serial
100% that would be suepr useful
