### ISSUE TITLE
Make the demo buttons work

### ISSUE THREAD

**Issue by mithro** [CarlFK/pici#27]
The demo buttons on each of the FPGAs pages should work...

![image](https://github.com/user-attachments/assets/7d224a23-ba4b-4d3e-99d7-7d5065a11886)

**Comment by CarlFK** [comment]
done enough to close this.
Need micropython on arty bitstream. 

It would be nice if the commands were sent one char at a time to look like someone typing.   that will be easy if someone does this:
https://github.com/huashengdun/webssh/issues/391
