### ISSUE TITLE
Use screen / tmux as shell on RPi

### ISSUE THREAD

**Issue by mithro** [CarlFK/pici#37]
By setting up the shell / login on the RPi so that it uses tmux then everyone who logs in will seen the same terminal messages.

I have a configuration that makes this for my own systems happen at https://github.com/mithro/rcfiles/tree/master/tmux -- it basically sets the login shell to zsh and then the [`.zprofile` file looks for an existing tmux to connect to](https://github.com/mithro/rcfiles/blob/master/tmux/zprofile).

**Comment by CarlFK** [comment]
done!
